### ISSUE TITLE
Ошибка при редактировании обработки VanessaBehavior с платформой 8.3.10

### ISSUE THREAD

**Issue by VladFrost** [silverbulleters/vanessa-behavior2#17]
ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма Возможно ошибочное свойство: "РежимИспользованияСинхронныхВызововРасширенийИВнешнихКомпонент"
см. http://downloads.v8.1c.ru/content//Platform/8_3_10_2561/1cv8upd.htm

**Comment by nixel2007** [comment]
Исправлено в #18
